In [2]:
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Input
import numpy as np

In [3]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [4]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
#X, y = split_sequence(raw_seq, n_steps)

windows = np.lib.stride_tricks.sliding_window_view(raw_seq, window_shape=n_steps)
X = array(windows[:-1])  # Todas las ventanas menos la última. Hay que convertir a array numpy
y = array(raw_seq[n_steps:])  # Lo que predices (el siguiente valor después de cada ventana)

print(X)
print(y)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


In [13]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# define model
model = Sequential()
model.add(Input(shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 465ms/step - loss: 4855.9087
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4806.6016
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4758.4609
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4711.0903
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4664.3989
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4618.1602
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4572.2300
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4526.4702
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4481.3701
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4439.1558
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4396.9556
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4354.6431
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4312.1255
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4269.4614
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 1

In [14]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.28305]]
